---
- name: "copy user files"
  sudo: no
  git:
    repo: http://github.com/tyjak/archlinux
    dest: /home/{{user_name}}/src/
  tags: "dotfiles"
- name: "link dot files"
  command: ln -s /home/{{user_name}}/src/archlinux/.config .config
  tags: "dotfiles"
- name: "copy vim files"
  sudo: no
  git:
    repo: http://github.com/tyjak/vim-config
    dest: /home/{{user_name}}/src/vim-config
  tags: "dotfiles"
- name: "link vim config"
  command: ln -s /home/{{user_name}}/src/vim-config/.vim .vim
  tags: "dotfiles"
