---
- name: "checkout dot files"
  sudo: no
  git:
    repo: http://github.com/tyjak/archlinux
    dest: /home/{{user_name}}/src/archlinux
  tags: "dotfiles"
- name: "checkout vim files"
  sudo: no
  git:
    repo: http://github.com/tyjak/vim-config
    dest: /home/{{user_name}}/src/vim-config
  tags: "dotfiles"
- name: "link dot files"
  sudo: no
  file:
    state: link
    src: /home/{{user_name}}/src/{{ item.src }}
    dest: ~/{{ item.dest }}
  with_items: link_items
  tags: "dotfiles"
