---
- name: "copy user files"
  synchronize:
    src: ../files/
    dest: /home/{{user_name}}/
    owner: no
    group: no
- name: "ensure ownership"
  sudo: yes
  file:
    state: directory
    recurse: yes
    path: "/home/{{user_name}}"
    owner: "{{user_name}}"
    group: "{{user_name}}"
